include $(TOPDIR)/rules.mk

LUCI_TITLE:=GL Portable Backup
LUCI_DESCRIPTION:=Portable configuration backup and restore for GL.iNet routers
PKG_VERSION:=1.0.0
LUCI_PKGARCH:=all
PKGARCH:=all

PKG_MAINTAINER:=RemoteToHome Consulting <https://remotetohome.io>
PKG_LICENSE:=GPL-3.0-or-later

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
